name: Publish Workflow
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: CPU Details
        run: lscpu
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.37"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE_ARN }}
      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          parse-json-secrets: true
          secret-ids: NPM_USER,${{ vars.NPM_USER_SECRET_ARN }}
      - uses: mangs/simple-release-notes-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          should_auto_update_major_tag: false
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          registry: https://registry.npmjs.org/
          token: ${{ env.NPM_USER_ACCESS_TOKEN }}
